# Generated by Django 3.1.5 on 2021-01-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Type here', max_length=100)),
                ('url', models.CharField(default='Type here', max_length=2048)),
                ('area', models.CharField(default='Type here', max_length=100)),
                ('notes', models.TextField()),
                ('aesthetic', models.CharField(default=' ', max_length=100)),
                ('country', models.CharField(default='N/A', max_length=15)),
                ('state', models.CharField(default='N/A', max_length=15)),
                ('wholesale', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('black_owned', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('minority_owned', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('woman_owned', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('small_business', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('sustainable', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('vegan', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Yes', 'Yes'), ('No', 'No'), ('Family', 'Family')], default='Not Applicable', max_length=100)),
                ('quarter_used', models.CharField(default='Enter Here', max_length=10)),
                ('box_used', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='cadeaux.vendor')),
            ],
        ),
    ]
