# Generated by Django 3.1.5 on 2021-01-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadeaux', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
